export const POST_LOGIN = 'POST_LOGIN'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_REGISTRATION = 'POST_REGISTRATION'
export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS'