export const SEND_SUSHI_CART = 'SEND_SUSHI_CART'
export const SEND_SUSHI_CART_SUCCESS = 'SEND_SUSHI_CART_SUCCESS'
export const SEND_TO_EXPO = 'SEND_TO_EXPO'
export const SEND_TO_EXPO_SUCCESS = 'SEND_TO_EXPO_SUCCESS'